/*
 * GENERATED by native/tools/generate_d3d9_bridge.ts - do not edit.
 * One line per bridged interface; the including file defines NFSU2_D3D9_IFACE.
 */
NFSU2_D3D9_IFACE(IDirect3D9)
NFSU2_D3D9_IFACE(IDirect3DBaseTexture9)
NFSU2_D3D9_IFACE(IDirect3DCubeTexture9)
NFSU2_D3D9_IFACE(IDirect3DDevice9)
NFSU2_D3D9_IFACE(IDirect3DIndexBuffer9)
NFSU2_D3D9_IFACE(IDirect3DPixelShader9)
NFSU2_D3D9_IFACE(IDirect3DQuery9)
NFSU2_D3D9_IFACE(IDirect3DResource9)
NFSU2_D3D9_IFACE(IDirect3DStateBlock9)
NFSU2_D3D9_IFACE(IDirect3DSurface9)
NFSU2_D3D9_IFACE(IDirect3DSwapChain9)
NFSU2_D3D9_IFACE(IDirect3DTexture9)
NFSU2_D3D9_IFACE(IDirect3DVertexBuffer9)
NFSU2_D3D9_IFACE(IDirect3DVertexDeclaration9)
NFSU2_D3D9_IFACE(IDirect3DVertexShader9)
NFSU2_D3D9_IFACE(IDirect3DVolume9)
NFSU2_D3D9_IFACE(IDirect3DVolumeTexture9)
